### ISSUE TITLE
All possible validation checks should be done before prompting the user to enter a message

### ISSUE THREAD

**Issue by jishi9** [google/git-appraise#21]
In [comment.go](https://github.com/google/git-appraise/blob/master/commands/comment.go#L47) the user may be prompted to enter a message via their configured text editor. The same issue applies to pull request #18 

Command line argument checks (e.g. "You cannot combine the flags -lgtm and -nmw") and other checks (e.g. "There is no matching review") are currently performed after the user had already entered their commit message.

These checks should be done before prompting the user for a message. Otherwise the user will be prompted to enter their message again and again, whilst they get the command arguments right, or whilst they figure out what the cause of the error message is.

**Comment by barbastan** [comment]
Thanks for these comments!

Barbara

**Comment by ojarjur** [comment]
Thanks for catching this. I believe we've moved all of the relevant validation checks up before editing the message, but if we missed something, then please feel encouraged to reopen this issue.
