### ISSUE TITLE
$EDITOR with args isn't working

### ISSUE THREAD

**Issue by the-kenny** [google/git-appraise#30]
My `EDITOR` is set to `emacsclient -tty`. This works fine with all common command line tools. It fails in git appraise with the following message:

```Unable to start editor: exec: "emacsclient -tty": executable file not found in $PATH```

**Comment by ojarjur** [comment]
Thanks for the report.

Right now we're taking the value of the editor var, and just trying to execute it, so that obviously won't work here. I'll look into how the stock git commands invoke the editor, and try to more accurately emulate what they do.

**Comment by ojarjur** [comment]
So, the stock git commands [use a shell to launch the editor](https://github.com/git/git/blob/8d530c4d64ffcc853889f7b385f554d53db375ed/editor.c#L46). However, they do so differently on [windows vs. non-windows](https://github.com/git/git/blob/aa826b651ae3012d1039453b36ed6f1eab939ef9/run-command.c#L346).

This will be hard to cleanly do in a cross-platform way. However, on the bright side, it *might* also fix [the issue](https://github.com/google/git-appraise/issues/19) that @linquize reported.

I'll try some ideas and see if any of them work.

**Comment by ojarjur** [comment]
This should be fixed with the latest change. I tested it with my editor set to "emacsclient -q" and did not see any issues.

If it still isn't working, then please re-open this issue.
