### ISSUE TITLE
git appraise review to act as a standard unix filter

### ISSUE THREAD

**Issue by eiro** [google/git-appraise#56]
hello,

i would like to use git appraise review with -F filename (- for stdin) instead of using an editor (as in git commit -F). this could be very usefull for many cases.

regards

**Comment by ojarjur** [comment]
I agree that we need this. Any command that supports "-m" should also support a "-F" (of just "-") option.

That is currently:

* `git appraise accept`
* `git appraise comment`
* `git appraise reject`
* `git appraise request`
