### ISSUE TITLE
Ability to write more detailed review comments

### ISSUE THREAD

**Issue by hazbo** [google/git-appraise#8]
When writing a comment on a review, you're able to pass `-m` followed by the message, as you'd expect. The `<file>` and `<line>` at this point are both optional however, so something like the following would be fine:

```bash
git appraise comment -m "Nice code!" 2c9bff89f0f8
```

Would it be unreasonable to suggest allowing the commenter to leave out the `-m`, much like how you'd write a proper commit message, by opening the text editor associated with git, to then write a more detailed comment?

**Comment by hazbo** [comment]
I noticed that the message is not actually required for a comment, is this the case due to there being both `-lgtm` and `-nmw` available instead of a message? If so, should it be the case that if either of those flags haven't been set, that a message is required?

**Comment by ojarjur** [comment]
That's a really good point.

Actually, I might state it more strongly than you have; posting a -nmw comment with no message is not helpful, and an -lgtm comment with no message can be posted with the "accept" subcommand, so I'm fine with the first proposal (if -m is missing, then open an editor).

I think the only reason we aren't already doing that is just that it didn't occur to me.

**Comment by hazbo** [comment]
That's weird you mention that, just earlier on I was thinking -nmw on it's own is actually really unhelpful. Maybe even a little rude!

So to be clear, are you proposing that the -lgtm (on it's own) is only going to be used with the accept subcommand? Or will it also still remain available for a comment too?

**Comment by ojarjur** [comment]
> So to be clear, are you proposing that the -lgtm (on it's own) is only going to be used with the accept subcommand? Or will it also still remain available for a comment too?

Yes, that's what I'm thinking. The accept command is just a shorthand for "comment -lgtm", so I'm fine with that being the only command that allows an empty comment.

**Comment by hazbo** [comment]
Yeah that seems to make the most sense to me.

**Comment by 0930-cheri** [comment]
Gibbycheri@gmail.com
