### ISSUE TITLE
Add documentation about how to specify line and column ranges for comments.

### ISSUE THREAD

**Issue by kevinbarabash** [google/git-appraise#87]
Phabricator has this feature and it's really useful being able to pinpoint exactly what lines you're talking about when you make a comment.

**Comment by ojarjur** [comment]
This is already supported. The command is of the form:

```sh
git appraise comment -f <FILE-NAME> -l <START-LINE>(+<START-COLUMN>)?(:<END-LINE>+<END-COLUMN>)?
```

So, for example, to comment from between the 5th and 6th characters of the second line of file "foo.txt" to between the 7th and 8th characters of the fourth line, you would run:

```sh
git appraise comment -f foo.txt -l 2+5:4+7
```

However, looking through the code, it seems that this is not documented in either the help text or the README file.

We should add it to our docs.
